function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry('cii_5zi_1', "Fluxon RC")
    AddTextEntry('cii_5zi_1_v', "Fluxon RC Accents")
    AddTextEntry('cii_5zi_2', "Zinger RS")
    AddTextEntry('cii_5zi_2_v', "Zinger RS Accents")
    AddTextEntry('cii_5zi_3', "Virex 520")
    AddTextEntry('cii_5zi_3_v', "Virex 520 Accents")
    AddTextEntry('cii_adv_1', "Marven V2CS")
    AddTextEntry('cii_adv_1_v', "Marven V2CS Accents")
    AddTextEntry('cii_adv_10', "Cyllen V2CS")
    AddTextEntry('cii_adv_10_v', "Cyllen V2CS Accents")
    AddTextEntry('cii_adv_11', "Tempra Spec CS")
    AddTextEntry('cii_adv_11_v', "Tempra Spec CS Accents")
    AddTextEntry('cii_adv_12', "Thresher Spec CS")
    AddTextEntry('cii_adv_12_v', "Thresher Spec CS Accents")
    AddTextEntry('cii_adv_13', "Phantom V2CS")
    AddTextEntry('cii_adv_13_v', "Phantom V2CS Accents")
    AddTextEntry('cii_adv_2', "Strava V1CS")
    AddTextEntry('cii_adv_2_v', "Strava V1CS Accents")
    AddTextEntry('cii_adv_3', "Strava V2CS")
    AddTextEntry('cii_adv_3_v', "Strava V2CS Accents")
    AddTextEntry('cii_adv_4', "Raptor Spec CS")
    AddTextEntry('cii_adv_4_v', "Raptor Spec CS Accents")
    AddTextEntry('cii_adv_5', "Dynarc MK5")
    AddTextEntry('cii_adv_5_v', "Dynarc MK5 Accents")
    AddTextEntry('cii_adv_6', "Dynarc Spec MK5")
    AddTextEntry('cii_adv_6_v', "Dynarc Spec MK5 Accents")
    AddTextEntry('cii_adv_7', "Forza X")
    AddTextEntry('cii_adv_7_v', "Forza X Accents")
    AddTextEntry('cii_adv_8', "Rava II")
    AddTextEntry('cii_adv_8_v', "Rava II Accents")
    AddTextEntry('cii_adv_9', "Supernova V2")
    AddTextEntry('cii_adv_9_v', "Supernova V2 Accents")
    AddTextEntry('cii_ame_1', "Outlaw II")
    AddTextEntry('cii_ame_1_v', "Outlaw II Accents")
    AddTextEntry('cii_ame_2', "Torqan MK1")
    AddTextEntry('cii_ame_2_v', "Torqan MK1 Accents")
    AddTextEntry('cii_asa_1', "Astral 118")
    AddTextEntry('cii_asa_1_v', "Astral 118 Accents")
    AddTextEntry('cii_asa_2', "Astral 134")
    AddTextEntry('cii_asa_2_v', "Astral 134 Accents")
    AddTextEntry('cii_asa_3', "Astral 140")
    AddTextEntry('cii_asa_3_v', "Astral 140 Accents")
    AddTextEntry('cii_ats_1', "Vintor Classic")
    AddTextEntry('cii_ats_1_v', "Vintor Classic Accents")
    AddTextEntry('cii_bbs_1', "Eonline 55")
    AddTextEntry('cii_bbs_1_v', "Eonline 55 Accents")
    AddTextEntry('cii_bbs_2', "Reva Mesh")
    AddTextEntry('cii_bbs_2_v', "Reva Mesh Accents")
    AddTextEntry('cii_bbs_3', "Ravik")
    AddTextEntry('cii_bbs_3_v', "Ravik Accents")
    AddTextEntry('cii_bbs_4', "Silvus GT")
    AddTextEntry('cii_bbs_4_v', "Silvus GT Accents")
    AddTextEntry('cii_bbs_5', "Tornova Fan")
    AddTextEntry('cii_bbs_5_v', "Tornova Fan Accents")
    AddTextEntry('cii_bor_1', "Arvon")
    AddTextEntry('cii_bor_1_v', "Arvon Accents")
    AddTextEntry('cii_bor_2', "Cabrin")
    AddTextEntry('cii_bor_2_v', "Cabrin Accents")
    AddTextEntry('cii_boy_1', "Slayra MK1")
    AddTextEntry('cii_boy_1_v', "Slayra MK1 Accents")
    AddTextEntry('cii_bra_1_s', "Solven S")
    AddTextEntry('cii_bra_1_s_v', "Solven S Accents")
    AddTextEntry('cii_bra_2', "Voltek IV")
    AddTextEntry('cii_bra_2_v', "Voltek IV Accents")
    AddTextEntry('cii_bra_3', "Voltek Multi VI")
    AddTextEntry('cii_bra_3_v', "Voltek Multi VI Accents")
    AddTextEntry('cii_bud_1', "Prime QF")
    AddTextEntry('cii_bud_1_v', "Prime QF Accents")
    AddTextEntry('cii_com_1', "Cyrex")
    AddTextEntry('cii_com_1_v', "Cyrex Accents")
    AddTextEntry('cii_com_2', "Morphis")
    AddTextEntry('cii_com_2_v', "Morphis Accents")
    AddTextEntry('cii_com_3', "Miralux")
    AddTextEntry('cii_com_3_v', "Miralux Accents")
    AddTextEntry('cii_com_4', "Threx II")
    AddTextEntry('cii_com_4_v', "Threx II Accents")
    AddTextEntry('cii_cra_1', "Seris Three")
    AddTextEntry('cii_cra_1_v', "Seris Three Accents")
    AddTextEntry('cii_cra_2', "Seris Five")
    AddTextEntry('cii_cra_2_v', "Seris Five Accents")
    AddTextEntry('cii_cra_3', "Seris Nine")
    AddTextEntry('cii_cra_3_v', "Seris Nine Accents")
    AddTextEntry('cii_cra_4', "Seris Six")
    AddTextEntry('cii_cra_4_v', "Seris Six Accents")
    AddTextEntry('cii_dub_1', "Bigchip MK1")
    AddTextEntry('cii_dub_1_v', "Bigchip MK1 Accents")
    AddTextEntry('cii_dub_2', "Presida Luxe")
    AddTextEntry('cii_dub_2_v', "Presida Luxe Accents")
    AddTextEntry('cii_dym_1', "Novix Spoke")
    AddTextEntry('cii_dym_1_v', "Novix Spoke Accents")
    AddTextEntry('cii_enk_1', "Navor Three")
    AddTextEntry('cii_enk_1_v', "Navor Three Accents")
    AddTextEntry('cii_enk_2', "Rovix")
    AddTextEntry('cii_enk_2_v', "Rovix Accents")
    AddTextEntry('cii_enk_3', "Rylux")
    AddTextEntry('cii_enk_3_v', "Rylux Accents")
    AddTextEntry('cii_enk_4', "Tarmak Evo")
    AddTextEntry('cii_enk_4_v', "Tarmak Evo Accents")
    AddTextEntry('cii_f52_1', "Evosync SC")
    AddTextEntry('cii_f52_1_v', "Evosync SC Accents")
    AddTextEntry('cii_f52_2', "Formila TR")
    AddTextEntry('cii_f52_2_v', "Formila TR Accents")
    AddTextEntry('cii_f52_3', "Forya")
    AddTextEntry('cii_f52_3_v', "Forya Accents")
    AddTextEntry('cii_f52_4', "Pentara")
    AddTextEntry('cii_f52_4_v', "Pentara Accents")
    AddTextEntry('cii_f52_5', "Tarmara")
    AddTextEntry('cii_f52_5_v', "Tarmara Accents")
    AddTextEntry('cii_f52_6', "Turbara MK1")
    AddTextEntry('cii_f52_6_v', "Turbara MK1 Accents")
    AddTextEntry('cii_f52_6_liv', "Turbara MK1 Livery")
    AddTextEntry('cii_f52_6_liv_v', "Turbara MK1 Livery Accents")
    AddTextEntry('cii_f52_7', "Turbara MK2")
    AddTextEntry('cii_f52_7_v', "Turbara MK2 Accents")
    AddTextEntry('cii_f52_8', "Outmar 1")
    AddTextEntry('cii_f52_8_v', "Outmar 1 Accents")
    AddTextEntry('cii_f52_9', "Tarmara 348")
    AddTextEntry('cii_f52_9_v', "Tarmara 348 Accents")
    AddTextEntry('cii_fik_1', "Formix Ten")
    AddTextEntry('cii_fik_1_v', "Formix Ten Accents")
    AddTextEntry('cii_fik_2', "Profira Five")
    AddTextEntry('cii_fik_2_v', "Profira Five Accents")
    AddTextEntry('cii_fik_3', "Profira S")
    AddTextEntry('cii_fik_3_v', "Profira S Accents")
    AddTextEntry('cii_gra_1', "Optimar")
    AddTextEntry('cii_gra_1_v', "Optimar Accents")
    AddTextEntry('cii_gra_2', "Cravix")
    AddTextEntry('cii_gra_2_v', "Cravix Accents")
    AddTextEntry('cii_gra_3', "Tarmix RC")
    AddTextEntry('cii_gra_3_v', "Tarmix RC Accents")
    AddTextEntry('cii_hal_1', "Indira")
    AddTextEntry('cii_hal_1_v', "Indira Accents")
    AddTextEntry('cii_hal_2', "Sprynter II")
    AddTextEntry('cii_hal_2_v', "Sprynter II Accents")
    AddTextEntry('cii_ham_1', "Editra R")
    AddTextEntry('cii_ham_1_v', "Editra R Accents")
    AddTextEntry('cii_ham_2', "Prigra")
    AddTextEntry('cii_ham_2_v', "Prigra Accents")
    AddTextEntry('cii_hol_1', "Hollstar")
    AddTextEntry('cii_hol_1_v', "Hollstar Accents")
    AddTextEntry('cii_hol_2', "Solidra")
    AddTextEntry('cii_hol_2_v', "Solidra Accents")
    AddTextEntry('cii_hol_3', "Sunra")
    AddTextEntry('cii_hol_3_v', "Sunra Accents")
    AddTextEntry('cii_hre_1', "Harix R")
    AddTextEntry('cii_hre_1_v', "Harix R Accents")
    AddTextEntry('cii_hre_10', "Havrix")
    AddTextEntry('cii_hre_10_v', "Havrix Accents")
    AddTextEntry('cii_hre_11', "Hexon")
    AddTextEntry('cii_hre_11_v', "Hexon Accents")
    AddTextEntry('cii_hre_12', "Hexra S")
    AddTextEntry('cii_hre_12_v', "Hexra S Accents")
    AddTextEntry('cii_hre_13', "Harven R")
    AddTextEntry('cii_hre_13_v', "Harven R Accents")
    AddTextEntry('cii_hre_14', "Harnix S")
    AddTextEntry('cii_hre_14_v', "Harnix S Accents")
    AddTextEntry('cii_hre_15', "Haltra RL")
    AddTextEntry('cii_hre_15_v', "Haltra RL Accents")
    AddTextEntry('cii_hre_16', "Hazra RL")
    AddTextEntry('cii_hre_16_v', "Hazra RL Accents")
    AddTextEntry('cii_hre_17', "Hedra RL")
    AddTextEntry('cii_hre_17_v', "Hedra RL Accents")
    AddTextEntry('cii_hre_18', "Hafra RL")
    AddTextEntry('cii_hre_18_v', "Hafra RL Accents")
    AddTextEntry('cii_hre_19', "Cresix")
    AddTextEntry('cii_hre_19_v', "Cresix Accents")
    AddTextEntry('cii_hre_2', "Cromax")
    AddTextEntry('cii_hre_2_v', "Cromax Accents")
    AddTextEntry('cii_hre_20', "Creston")
    AddTextEntry('cii_hre_20_v', "Creston Accents")
    AddTextEntry('cii_hre_21', "Cronix")
    AddTextEntry('cii_hre_21_v', "Cronix Accents")
    AddTextEntry('cii_hre_22', "Falra One")
    AddTextEntry('cii_hre_22_v', "Falra One Accents")
    AddTextEntry('cii_hre_23', "Portra One")
    AddTextEntry('cii_hre_23_v', "Portra One Accents")
    AddTextEntry('cii_hre_24', "Portra Four")
    AddTextEntry('cii_hre_24_v', "Portra Four Accents")
    AddTextEntry('cii_hre_25', "Portra Seven")
    AddTextEntry('cii_hre_25_v', "Portra Seven Accents")
    AddTextEntry('cii_hre_26', "Prymax SC")
    AddTextEntry('cii_hre_26_v', "Prymax SC Accents")
    AddTextEntry('cii_hre_27', "Pryven SC")
    AddTextEntry('cii_hre_27_v', "Pryven SC Accents")
    AddTextEntry('cii_hre_3', "Pryzon SC")
    AddTextEntry('cii_hre_3_v', "Pryzon SC Accents")
    AddTextEntry('cii_hre_4', "Prydel SC")
    AddTextEntry('cii_hre_4_v', "Prydel SC Accents")
    AddTextEntry('cii_hre_5', "Pryvox SC")
    AddTextEntry('cii_hre_5_v', "Pryvox SC Accents")
    AddTextEntry('cii_hre_6', "Ravrix")
    AddTextEntry('cii_hre_6_v', "Ravrix Accents")
    AddTextEntry('cii_hre_7', "Sylon One")
    AddTextEntry('cii_hre_7_v', "Sylon One Accents")
    AddTextEntry('cii_hre_8', "Sylon Four")
    AddTextEntry('cii_hre_8_v', "Sylon Four Accents")
    AddTextEntry('cii_hre_9', "Sylon Seven")
    AddTextEntry('cii_hre_9_v', "Sylon Seven Accents")
    AddTextEntry('cii_ifo_1', "Astrona")
    AddTextEntry('cii_ifo_1_v', "Astrona Accents")
    AddTextEntry('cii_ifo_2', "Fabulor RS")
    AddTextEntry('cii_ifo_2_v', "Fabulor RS Accents")
    AddTextEntry('cii_kmc_1', "Xendra")
    AddTextEntry('cii_kmc_1_v', "Xendra Accents")
    AddTextEntry('cii_kon_1', "Afterra")
    AddTextEntry('cii_kon_1_v', "Afterra Accents")
    AddTextEntry('cii_kon_2', "Britora")
    AddTextEntry('cii_kon_2_v', "Britora Accents")
    AddTextEntry('cii_kon_3', "Daylora")
    AddTextEntry('cii_kon_3_v', "Daylora Accents")
    AddTextEntry('cii_kos_1', "Kentra Sport")
    AddTextEntry('cii_kos_1_v', "Kentra Sport Accents")
    AddTextEntry('cii_kos_2', "Rotrex")
    AddTextEntry('cii_kos_2_v', "Rotrex Accents")
    AddTextEntry('cii_lex_1', "Lextro One")
    AddTextEntry('cii_lex_1_v', "Lextro One Accents")
    AddTextEntry('cii_lex_3', "Lextro Four")
    AddTextEntry('cii_lex_3_v', "Lextro Four Accents")
    AddTextEntry('cii_lex_4', "Mistora")
    AddTextEntry('cii_lex_4_v', "Mistora Accents")
    AddTextEntry('cii_mic_1', "Clastor")
    AddTextEntry('cii_mic_1_v', "Clastor Accents")
    AddTextEntry('cii_mic_2', "Dragra ET")
    AddTextEntry('cii_mic_2_v', "Dragra ET Accents")
    AddTextEntry('cii_mod_1', "Mora Three")
    AddTextEntry('cii_mod_1_v', "Mora Three Accents")
    AddTextEntry('cii_mod_2', "Mora Seven")
    AddTextEntry('cii_mod_2_v', "Mora Seven Accents")
    AddTextEntry('cii_mom_1', "Gentra")
    AddTextEntry('cii_mom_1_v', "Gentra Accents")
    AddTextEntry('cii_mom_2', "Quantira")
    AddTextEntry('cii_mom_2_v', "Quantira Accents")
    AddTextEntry('cii_mom_3', "Ravtor RS")
    AddTextEntry('cii_mom_3_v', "Ravtor RS Accents")
    AddTextEntry('cii_mom_4', "Revenix")
    AddTextEntry('cii_mom_4_v', "Revenix Accents")
    AddTextEntry('cii_mom_5', "Rustra GT")
    AddTextEntry('cii_mom_5_v', "Rustra GT Accents")
    AddTextEntry('cii_mom_6', "Stingar")
    AddTextEntry('cii_mom_6_v', "Stingar Accents")
    AddTextEntry('cii_mom_7', "Tensar")
    AddTextEntry('cii_mom_7_v', "Tensar Accents")
    AddTextEntry('cii_mot_1', "Morrin Nine")
    AddTextEntry('cii_mot_1_v', "Morrin Nine Accents")
    AddTextEntry('cii_mot_2', "Spentra")
    AddTextEntry('cii_mot_2_v', "Spentra Accents")
    AddTextEntry('cii_mot_3', "Trackla One")
    AddTextEntry('cii_mot_3_v', "Trackla One Accents")
    AddTextEntry('cii_mot_4', "Trackla Two")
    AddTextEntry('cii_mot_4_v', "Trackla Two Accents")
    AddTextEntry('cii_oet_1', "Tyrox X")
    AddTextEntry('cii_oet_1_v', "Tyrox X Accents")
    AddTextEntry('cii_oet_2', "Tyrox E")
    AddTextEntry('cii_oet_2_v', "Tyrox E Accents")
    AddTextEntry('cii_oz_1', "Orzona")
    AddTextEntry('cii_oz_1_v', "Orzona Accents")
    AddTextEntry('cii_oz_2', "Orzona Deep")
    AddTextEntry('cii_oz_2_v', "Orzona Deep Accents")
    AddTextEntry('cii_oz_3', "Leggera III")
    AddTextEntry('cii_oz_3_v', "Leggera III Accents")
    AddTextEntry('cii_oz_4', "Turrismo GT")
    AddTextEntry('cii_oz_4_v', "Turrismo GT Accents")
    AddTextEntry('cii_rac_1', "Ragron S")
    AddTextEntry('cii_rac_1_v', "Ragron S Accents")
    AddTextEntry('cii_rac_2', "Rystar")
    AddTextEntry('cii_rac_2_v', "Rystar Accents")
    AddTextEntry('cii_ro_1', "Ravon Five")
    AddTextEntry('cii_ro_1_v', "Ravon Five Accents")
    AddTextEntry('cii_ro_2', "Ravon Seven")
    AddTextEntry('cii_ro_2_v', "Ravon Seven Accents")
    AddTextEntry('cii_rot_1', "Balinque")
    AddTextEntry('cii_rot_1_v', "Balinque Accents")
    AddTextEntry('cii_rot_10', "Bermix")
    AddTextEntry('cii_rot_10_v', "Bermix Accents")
    AddTextEntry('cii_rot_11', "Cabrix")
    AddTextEntry('cii_rot_11_v', "Cabrix Accents")
    AddTextEntry('cii_rot_12', "Furniq")
    AddTextEntry('cii_rot_12_v', "Furniq Accents")
    AddTextEntry('cii_rot_13', "Indux")
    AddTextEntry('cii_rot_13_v', "Indux Accents")
    AddTextEntry('cii_rot_2', "Jaspera")
    AddTextEntry('cii_rot_2_v', "Jaspera Accents")
    AddTextEntry('cii_rot_3', "Mileva")
    AddTextEntry('cii_rot_3_v', "Mileva Accents")
    AddTextEntry('cii_rot_4', "Nuvix")
    AddTextEntry('cii_rot_4_v', "Nuvix Accents")
    AddTextEntry('cii_rot_5', "Phazer")
    AddTextEntry('cii_rot_5_v', "Phazer Accents")
    AddTextEntry('cii_rot_6', "Scronix")
    AddTextEntry('cii_rot_6_v', "Scronix Accents")
    AddTextEntry('cii_rot_7', "Tarmox")
    AddTextEntry('cii_rot_7_v', "Tarmox Accents")
    AddTextEntry('cii_rot_8', "Usfira")
    AddTextEntry('cii_rot_8_v', "Usfira Accents")
    AddTextEntry('cii_rot_9', "Vireta")
    AddTextEntry('cii_rot_9_v', "Vireta Accents")
    AddTextEntry('cii_rsw_1', "Cyclora")
    AddTextEntry('cii_rsw_1_v', "Cyclora Accents")
    AddTextEntry('cii_spe_1', "Spectra Fourteen")
    AddTextEntry('cii_spe_1_v', "Spectra Fourteen Accents")
    AddTextEntry('cii_spe_2', "Spectra Eight")
    AddTextEntry('cii_spe_2_v', "Spectra Eight Accents")
    AddTextEntry('cii_spe_3', "Formix One")
    AddTextEntry('cii_spe_3_v', "Formix One Accents")
    AddTextEntry('cii_tea_1', "Cotera")
    AddTextEntry('cii_tea_1_v', "Cotera Accents")
    AddTextEntry('cii_tea_2', "Prorace One")
    AddTextEntry('cii_tea_2_v', "Prorace One Accents")
    AddTextEntry('cii_tea_3', "Prorace Two")
    AddTextEntry('cii_tea_3_v', "Prorace Two Accents")
    AddTextEntry('cii_ten_4', "Dencor Six")
    AddTextEntry('cii_ten_4_v', "Dencor Six Accents")
    AddTextEntry('cii_ten_5', "Rensix Five")
    AddTextEntry('cii_ten_5_v', "Rensix Five Accents")
    AddTextEntry('cii_tsw_1', "Catalora")
    AddTextEntry('cii_tsw_1_v', "Catalora Accents")
    AddTextEntry('cii_tsw_2', "Hockenra")
    AddTextEntry('cii_tsw_2_v', "Hockenra Accents")
    AddTextEntry('cii_tsw_3', "Trackmor Four")
    AddTextEntry('cii_tsw_3_v', "Trackmor Four Accents")
    AddTextEntry('cii_vol_1', "Reltra")
    AddTextEntry('cii_vol_1_v', "Reltra Accents")
    AddTextEntry('cii_vol_2', "Tervon")
    AddTextEntry('cii_vol_2_v', "Tervon Accents")
    AddTextEntry('cii_vol_3', "Turnix Fan")
    AddTextEntry('cii_vol_3_v', "Turnix Fan Accents")
    AddTextEntry('cii_vol_3_liv', "Turnix Fan Livery")
    AddTextEntry('cii_vol_3_liv_v', "Turnix Fan Livery Accents")
    AddTextEntry('cii_wed_1', "Sarvon")
    AddTextEntry('cii_wed_1_v', "Sarvon Accents")
    AddTextEntry('cii_wed_2', "Sarvon F")
    AddTextEntry('cii_wed_2_v', "Sarvon F Accents")
    AddTextEntry('cii_wed_3', "Torrix")
    AddTextEntry('cii_wed_3_v', "Torrix Accents")
    AddTextEntry('cii_wel_1', "Alumax Drag")
    AddTextEntry('cii_wel_1_v', "Alumax Drag Accents")
    AddTextEntry('cii_wel_2', "Alumax BL")
    AddTextEntry('cii_wel_2_v', "Alumax BL Accents")
    AddTextEntry('cii_wel_3', "Magnor Three")
    AddTextEntry('cii_wel_3_v', "Magnor Three Accents")
    AddTextEntry('cii_wor_1', "Crovix")
    AddTextEntry('cii_wor_1_v', "Crovix Accents")
    AddTextEntry('cii_wor_2', "Dezra DH")
    AddTextEntry('cii_wor_2_v', "Dezra DH Accents")
    AddTextEntry('cii_wor_3', "Equipra One")
    AddTextEntry('cii_wor_3_v', "Equipra One Accents")
    AddTextEntry('cii_wor_4', "Xedra")
    AddTextEntry('cii_wor_4_v', "Xedra Accents")
    AddTextEntry('cii_zsp_1', "Aerova")
    AddTextEntry('cii_zsp_1_v', "Aerova Accents")
end)