server_script '@jamaica-pedovi/src/include/server.lua'


fx_version 'adamant'
game 'gta5'
description 'Car Sounds Pack'
author 'Mrkvica'
 
files {
	"audioconfig/*.dat151.rel",
	"audioconfig/*.dat54.rel",
	"audioconfig/*.dat10.rel",
	"sfx/**/*.awc"
}


data_file 'AUDIO_GAMEDATA' 'audioconfig/elegyrh7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/elegyrh7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rh7elegy'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jdoraclev12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jdoraclev12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jdoraclev12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sentinelsg4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sentinelsg4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sentinelsg4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/elegyx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/elegyx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_elegyx'
data_file 'AUDIO_GAMEDATA' 'audioconfig/elegyx_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/majimalm_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/majimalm_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_majimagt'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/monroec_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/monroec_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/monroec_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_monroec'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trumpetzrc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trumpetzr_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trumpetzrc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trumpetzr_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trumpetzr'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ariant_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ariant_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ariant'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cw2019_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cw2019_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cw2019'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v8sultanrs'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/stratumc_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/stratumc_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/stratumc_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_zircoflow'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gresleyh_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gresleyh_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gresleyh_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gresleyh'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s85b50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aston59v12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aston59v12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aston59v12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lambov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lambov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lambov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/b58b30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/b58b30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_b58b30'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ea888_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ea888_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ea888'
data_file 'AUDIO_GAMEDATA' 'audioconfig/skart_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/skart_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_skart'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20c'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/mbnzc63eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mbnzc63eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mbnzc63eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mbnzc63eng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb28dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb28dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb28dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta183lt1_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta183lt1_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta183lt1'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lamavgineng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lamavgineng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lamavgineng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lamavgineng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/suzukigsxr1k_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/suzukigsxr1k_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_suzukigsxr1k'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq35ferf154cd_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq35ferf154cd_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq35ferf154cd'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc74s1000rrakevoline_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc74s1000rrakevoline_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc74s1000rrakevoline'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta103ninjah2r_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta103ninjah2r_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta103ninjah2r'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lg81hcredeye_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg81hcredeye_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg81hcredeye_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg81hcredeye'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lg62chironpursport_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg62chironpursport_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg62chironpursport_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg62chironpursport'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bmws1krreng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bmws1krreng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bmws1krreng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bmws1krreng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc32ducavr4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc32ducavr4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc32ducavr4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mercm177_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercm177_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercm177'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/f136_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f136_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f136_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f136'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lg57mustangtv8_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg57mustangtv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg57mustangtv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg57mustangtv8'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gt3rstun_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gt3rstun_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gt3rstun_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gt3rstun'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lg59hurv10_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg59hurv10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg59hurv10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg59hurv10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta122s58_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta122s58_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta122s58'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqm275amg_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqm275amg_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqm275amg'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/z33u2_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/z33u2_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/z33u2_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_z33u2'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/kc28sr180_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc28sr180_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc28sr180_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc28sr180'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/suzukigsxr1k_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/suzukigsxr1k_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_suzukigsxr1k'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq48roln72v12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq48roln72v12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq48roln72v12'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/a80ffeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/a80ffeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/a80ffeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_a80ffeng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ea825_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ea825_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ea825'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lg18bmwm4_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg18bmwm4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg18bmwm4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg18bmwm4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc26golft_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc26golft_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc26golft'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s55b30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s55b30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s55b30'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lg30meramgtr_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg30meramgtr_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg30meramgtr_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg30meramgtr'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/ml720v8eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ml720v8eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ml720v8eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ml720v8eng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sunrise_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sunrise_sounds.dat54.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sunrise'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bm3g80valvetronic_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bm3g80valvetronic_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bm3g80valvetronic'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sentinelsg4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sentinelsg4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sentinelsg4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/argento_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/argento_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_argento'
data_file 'AUDIO_GAMEDATA' 'audioconfig/elegyx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/elegyx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_elegyx'
data_file 'AUDIO_GAMEDATA' 'audioconfig/majimalm_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/majimalm_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_majimagt'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/monroec_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/monroec_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/monroec_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_monroec'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trumpetzrc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trumpetzr_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trumpetzrc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trumpetzr_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trumpetzr'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ariant_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ariant_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ariant'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cw2019_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cw2019_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cw2019'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v8sultanrs'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/stratumc_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/stratumc_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/stratumc_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_zircoflow'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gresleyh_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gresleyh_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gresleyh_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gresleyh'
data_file 'AUDIO_GAMEDATA' 'audioconfig/skart_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/skart_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_skart'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lfasound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/r34sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r34sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r34sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/hemisound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/hemisound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_hemisound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s15sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s15sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s15sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aventadorv12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aventadorv12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aventadorv12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/svjsound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/svjsound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_svjsound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ftypesound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ftypesound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ftypesound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lambov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lambov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lambov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f10m5_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f10m5_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f10m5'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s85b50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/npolchar_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/npolchar_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_npolchar'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ecoboostv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ecoboostv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ecoboostv6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cvpiv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cvpiv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cvpiv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/subaruej20_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/subaruej20_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_subaruej20'
data_file 'AUDIO_GAMEDATA' 'audioconfig/fordvoodoo_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/fordvoodoo_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_fordvoodoo'
data_file 'AUDIO_GAMEDATA' 'audioconfig/n4g63t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/n4g63t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_n4g63t'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta488f154_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta488f154_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta488f154'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq59pagm297_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq59pagm297_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq59pagm297'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq70bmws58_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq70bmws58_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq70bmws58'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq71for427fe_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq71for427fe_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq71for427fe'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqtoy2jzstock_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqtoy2jzstock_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqtoy2jzstock'
data_file "AUDIO_SYNTHDATA" "audioconfig/audr8tteng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/audr8tteng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/audr8tteng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_audr8tteng"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bgw16_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bgw16_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bgw16_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bgw16'
data_file "AUDIO_SYNTHDATA" "audioconfig/bmws1krreng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/bmws1krreng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/bmws1krreng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_bmws1krreng"
data_file 'AUDIO_GAMEDATA' 'audioconfig/chevroletlt4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/chevroletlt4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_chevroletlt4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ecoboostv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ecoboostv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ecoboostv6'
data_file "AUDIO_SYNTHDATA" "audioconfig/f50gteng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/f50gteng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/f50gteng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_f50gteng"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/fd3sid_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/fd3sid_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/fd3sid_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_fd3sid'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta023l539_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta023l539_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta023l539'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta006bmws65_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta006bmws65_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta006bmws65'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta103ninjah2r_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta103ninjah2r_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta103ninjah2r'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta008mustang69_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta008mustang69_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta008mustang69'
data_file 'AUDIO_GAMEDATA' 'audioconfig/r35sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r35sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r35sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/talam52v10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/talam52v10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_talam52v10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/taaud40v8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/taaud40v8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_taaud40v8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/m840trsenna_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m840trsenna_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m840trsenna'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg125mnsrybently_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg125mnsrybently_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg125mnsrybently_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg125mnsrybently"
data_file "AUDIO_GAMEDATA" "audioconfig/kc144kawazx10rsc_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc144kawazx10rsc_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc144kawazx10rsc"
data_file 'AUDIO_GAMEDATA' 'audioconfig/gallardov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gallardov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gallardov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lfasound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg30meramgtr_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg30meramgtr_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg30meramgtr_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg30meramgtr"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg54evoxtun_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg54evoxtun_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg54evoxtun_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg54evoxtun"
data_file "AUDIO_SYNTHDATA" "audioconfig/kc24r33gts_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/kc24r33gts_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc24r33gts_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc24r33gts"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg53fer488capri_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg53fer488capri_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg53fer488capri_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg53fer488capri"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg62chironpursport_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg62chironpursport_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg62chironpursport_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg62chironpursport"
data_file 'AUDIO_GAMEDATA' 'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v8sultanrs'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/czr1eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/czr1eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/czr1eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_czr1eng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta183lt1_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta183lt1_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta183lt1'
data_file 'AUDIO_GAMEDATA' 'audioconfig/twinhuracan_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/twinhuracan_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_twinhuracan'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta488f154_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta488f154_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta488f154'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq40benw12tt_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq40benw12tt_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq40benw12tt'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg91timreg_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg91timreg_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg91timreg_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg91timreg"
data_file 'AUDIO_GAMEDATA' 'audioconfig/m5cracklemod_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m5cracklemod_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m5cracklemod'
data_file 'AUDIO_GAMEDATA' 'audioconfig/prg25tfsi_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/prg25tfsi_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_prg25tfsi'
data_file "AUDIO_SYNTHDATA" "audioconfig/kc98gmls6_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/kc98gmls6_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc98gmls6_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc98gmls6"
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq58honk20a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq58honk20a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq58honk20a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/prg4b11t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/prg4b11t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_prg4b11t'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq93bmws55_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq93bmws55_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq93bmws55'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq77bmws85_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq77bmws85_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq77bmws85'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta011mit4g63_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta011mit4g63_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta011mit4g63'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sunrise_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sunrise_sounds.dat'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg86fer812sf_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg86fer812sf_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg86fer812sf_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg86fer812sf"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg51uruscapri_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg51uruscapri_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg51uruscapri_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg51uruscapri"
data_file 'AUDIO_GAMEDATA' 'audioconfig/evoixsound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/evoixsound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_evoixsound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq2jzgterace_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq2jzgterace_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq2jzgterace'

--- mrkva gt3 rs zvuk ---
data_file "AUDIO_SYNTHDATA" "audioconfig/kc259gt3swf1_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/kc259gt3swf1_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc259gt3swf1_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc259gt3swf1"
--- mrkva gt3 rs zvuk ---


--- mrkva m5 g90 zvuk ---
data_file "AUDIO_SYNTHDATA" "audioconfig/kc201m4f82_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/kc201m4f82_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc201m4f82_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc201m4f82"
--- mrkva m5 g90 zvuk ---

--- mrkva c7 zvuk ---
data_file 'AUDIO_GAMEDATA' 'audioconfig/str4ls7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/str4ls7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_str4ls7'
--- mrkva c7 zvuk ---


data_file "AUDIO_SYNTHDATA" "audioconfig/lg58mwm3gtrdemo_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg58mwm3gtrdemo_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg58mwm3gtrdemo_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg58mwm3gtrdemo"


data_file 'AUDIO_GAMEDATA' 'audioconfig/aqls7raceswap_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqls7raceswap_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqls7raceswap'

data_file 'AUDIO_SYNTHDATA' 'audioconfig/nisgtr35_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/nisgtr35_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nisgtr35_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nisgtr35'

--- buba mk5 ---
data_file "AUDIO_SYNTHDATA" "audioconfig/lg16a90mk5_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg16a90mk5_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg16a90mk5_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg16a90mk5"
--- buba mk5 ---

--- AUTOMAFIA BMW 330i ---
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq78bmws65_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq78bmws65_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq78bmws65'
--- AUTOMAFIA BMW 330i ---

--- SUNRISE2 MRKVA ---
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta4b11_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta4b11_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta4b11'
--- SUNRISE2 MRKVA ---

server_scripts {
    'helpers/hook_system.js'
}