-- =========================================================================
-- Cayo Tunnel — Entity Sets
-- =========================================================================
-- Default entity set configuration for the Cayo Perico Tunnel modules.
-- Adapted from tstudio_cayo_tunnel/config.lua (M100 + Crime Exit modules).
-- Format matches the other tstudio_zmapdata entitysets/ files.
--
-- m100 modules — Pillars (1 of 2) + Insets (1 of 3):
--   m100_pillar_basic / m100_pillar_wallsign
--   m100_ins01_basic / m100_ins01_exitladder / m100_ins01_exitdoor
-- mcexit modules — crime props + airlock state:
--   mcexit_set_drugs / mcexit_set_weapons / mcexit_set_smug
--   mcexit_set_airlock_open / mcexit_set_airlock_close
-- =========================================================================

return {
    {
        name = "M100 Module 01",
        coords = vector3(1574.7312, -2910.397, -47),
        ipl = "tstudio_qx_cayotun_m100_01_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 02",
        coords = vector3(1662.5155, -2978.98169, -47),
        ipl = "tstudio_qx_cayotun_m100_02_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 03",
        coords = vector3(1821.2207, -3102.97583, -47),
        ipl = "tstudio_qx_cayotun_m100_03_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 04",
        coords = vector3(1900.57336, -3164.973, -47),
        ipl = "tstudio_qx_cayotun_m100_04_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 05",
        coords = vector3(1979.926, -3226.97, -47),
        ipl = "tstudio_qx_cayotun_m100_05_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 06",
        coords = vector3(2059.27881, -3288.96729, -47),
        ipl = "tstudio_qx_cayotun_m100_06_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 07",
        coords = vector3(2147.06323, -3357.55176, -47),
        ipl = "tstudio_qx_cayotun_m100_07_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 08",
        coords = vector3(2305.7688, -3481.54639, -47),
        ipl = "tstudio_qx_cayotun_m100_08_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 09",
        coords = vector3(2385.12183, -3543.54346, -47),
        ipl = "tstudio_qx_cayotun_m100_09_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 10",
        coords = vector3(2464.47437, -3605.541, -47),
        ipl = "tstudio_qx_cayotun_m100_10_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 11",
        coords = vector3(2543.82739, -3667.53784, -47),
        ipl = "tstudio_qx_cayotun_m100_11_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 12",
        coords = vector3(2631.61157, -3736.1228, -47),
        ipl = "tstudio_qx_cayotun_m100_12_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 13",
        coords = vector3(2710.96436, -3798.11963, -47),
        ipl = "tstudio_qx_cayotun_m100_13_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 14",
        coords = vector3(2790.317, -3860.117, -47),
        ipl = "tstudio_qx_cayotun_m100_14_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 15",
        coords = vector3(2869.66968, -3922.11377, -47),
        ipl = "tstudio_qx_cayotun_m100_15_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 16",
        coords = vector3(3028.375, -4046.108, -47),
        ipl = "tstudio_qx_cayotun_m100_16_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 17",
        coords = vector3(3116.15918, -4114.693, -47),
        ipl = "tstudio_qx_cayotun_m100_17_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 18",
        coords = vector3(3195.51172, -4176.69, -47),
        ipl = "tstudio_qx_cayotun_m100_18_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 19",
        coords = vector3(3274.8645, -4238.687, -47),
        ipl = "tstudio_qx_cayotun_m100_19_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 20",
        coords = vector3(3354.21729, -4300.684, -47),
        ipl = "tstudio_qx_cayotun_m100_20_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 21",
        coords = vector3(3512.92285, -4424.678, -47),
        ipl = "tstudio_qx_cayotun_m100_21_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 22",
        coords = vector3(3600.70752, -4493.263, -47),
        ipl = "tstudio_qx_cayotun_m100_22_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 23",
        coords = vector3(1495.37854, -2848.4, -47),
        ipl = "tstudio_qx_cayotun_m100_23_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = true},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = true},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 24",
        coords = vector3(3680.0603, -4555.26025, -47),
        ipl = "tstudio_qx_cayotun_m100_24_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = false},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = true},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = false},
        },
    },
    {
        name = "M100 Module 25",
        coords = vector3(3759.41284, -4617.25732, -47),
        ipl = "tstudio_qx_cayotun_m100_25_milo_",
        entitySets = {
            {name = "m100_pillar_basic", enable = true},
            {name = "m100_pillar_wallsign", enable = false},
            {name = "m100_ins01_basic", enable = true},
            {name = "m100_ins01_exitladder", enable = false},
            {name = "m100_ins01_exitdoor", enable = false},
            {name = "m100_service_closed_ls", enable = false},
            {name = "m100_service_closed_cayo", enable = true},
        },
    },
    {
        name = "Crime Exit 01",
        coords = vector3(1618.62329, -2944.68921, -47),
        ipl = "tstudio_qx_cayotun_mcexit_01_milo_",
        entitySets = {
            {name = "mcexit_set_drugs", enable = false},
            {name = "mcexit_set_weapons", enable = false},
            {name = "mcexit_set_smug", enable = false},
            {name = "mcexit_set_airlock_open", enable = false},
            {name = "mcexit_set_airlock_close", enable = true},
        },
    },
    {
        name = "Crime Exit 02",
        coords = vector3(2103.17114, -3323.25928, -47),
        ipl = "tstudio_qx_cayotun_mcexit_02_milo_",
        entitySets = {
            {name = "mcexit_set_drugs", enable = false},
            {name = "mcexit_set_weapons", enable = false},
            {name = "mcexit_set_smug", enable = false},
            {name = "mcexit_set_airlock_open", enable = true},
            {name = "mcexit_set_airlock_close", enable = false},
        },
    },
    {
        name = "Crime Exit 03",
        coords = vector3(2587.71973, -3701.83, -47),
        ipl = "tstudio_qx_cayotun_mcexit_03_milo_",
        entitySets = {
            {name = "mcexit_set_drugs", enable = false},
            {name = "mcexit_set_weapons", enable = false},
            {name = "mcexit_set_smug", enable = false},
            {name = "mcexit_set_airlock_open", enable = true},
            {name = "mcexit_set_airlock_close", enable = false},
        },
    },
    {
        name = "Crime Exit 04",
        coords = vector3(3072.267, -4080.40039, -47),
        ipl = "tstudio_qx_cayotun_mcexit_04_milo_",
        entitySets = {
            {name = "mcexit_set_drugs", enable = false},
            {name = "mcexit_set_weapons", enable = false},
            {name = "mcexit_set_smug", enable = false},
            {name = "mcexit_set_airlock_open", enable = true},
            {name = "mcexit_set_airlock_close", enable = false},
        },
    },
    {
        name = "Crime Exit 05",
        coords = vector3(3556.81519, -4458.9707, -47),
        ipl = "tstudio_qx_cayotun_mcexit_05_milo_",
        entitySets = {
            {name = "mcexit_set_drugs", enable = false},
            {name = "mcexit_set_weapons", enable = false},
            {name = "mcexit_set_smug", enable = false},
            {name = "mcexit_set_airlock_open", enable = true},
            {name = "mcexit_set_airlock_close", enable = false},
        },
    },
    {
        name = "Checkpoint Container LS",
        coords = vector3(795.8579, -2792.10669, 5.35580826),
        ipl = "tstudio_qx_cayotun_checkpoint_container01_milo_",
        entitySets = {
            {name = "container_bp", enable = true},   -- Border Patrol (LS)
            {name = "container_mp", enable = false},  -- Cayo rubis
        },
    },
    {
        name = "Checkpoint Container CAYO",
        coords = vector3(4412.40771, -4656.51025, 6.48764753),
        ipl = "tstudio_qx_cayotun_checkpoint_container02_milo_",
        entitySets = {
            {name = "container_bp", enable = false},  -- Border Patrol
            {name = "container_mp", enable = true},   -- Cayo rubis (Cayo)
        },
    },
}
