Config = {}

Config.Debug = false -- true = debug prints
Config.Language = 'en' -- en / de / pl / fr / es / it / nl / ru / tr / ar
Config.Manufacturer = true -- true = show manufacturer on vehicle details [set false if it seems to be duplicated]
Config.PoliceRecordsDefaultTab = 'warrants' -- 'warrants' / 'reports' / 'bolos' / 'incidents'

Config.canOpenTablet = function()
    local playerState = LocalPlayer.state
    if playerState.isDead or playerState.isCuffed then
        return false
    end
    
    return true
end

Config.Permissions = {
    ['sud'] = {
        ['0'] = {
            ['citizens'] = true,
            ['vehicles'] = true,
            ['reports'] = true,
            ['courts'] = true,
            ['inspections'] = false,
            ['companies'] = false,
            ['finances'] = false,
            ['announcements'] = true,
            ['employees'] = false,
            ['society'] = false,
            ['police_records'] = true,

            ['send_citizen_message'] = false,
            ['add_citizen_license'] = false, ['remove_citizen_license'] = false,
            ['change_citizen_picture'] = false, ['add_citizen_note'] = true, ['delete_citizen_note'] = false,
            ['add_citizen_tag'] = false, ['delete_citizen_tag'] = false,
            ['fire_player'] = false, ['hire_player'] = false, ['promote_player'] = false,
            ['create_announcement'] = false, ['delete_announcement'] = false,
            ['change_company_picture'] = false,
            ['withdraw_money'] = false, ['deposit_money'] = false, ['account_balance'] = false,
            ['society_transactions'] = false, ['society_chart'] = false,
            ['charge_account'] = false, ['donate_account'] = false, ['save_account_note'] = false,
            ['create_inspection'] = false, ['transfer_vehicle'] = false,
        },
        ['1'] = {
            ['citizens'] = true,
            ['vehicles'] = true,
            ['reports'] = true,
            ['courts'] = true,
            ['inspections'] = false,
            ['companies'] = false,
            ['finances'] = false,
            ['announcements'] = true,
            ['employees'] = true,
            ['society'] = false,
            ['police_records'] = true,

            ['send_citizen_message'] = true,
            ['add_citizen_license'] = false, ['remove_citizen_license'] = false,
            ['change_citizen_picture'] = false, ['add_citizen_note'] = true, ['delete_citizen_note'] = true,
            ['add_citizen_tag'] = true, ['delete_citizen_tag'] = true,
            ['fire_player'] = false, ['hire_player'] = false, ['promote_player'] = false,
            ['create_announcement'] = false, ['delete_announcement'] = false,
            ['change_company_picture'] = false,
            ['withdraw_money'] = false, ['deposit_money'] = false, ['account_balance'] = false,
            ['society_transactions'] = false, ['society_chart'] = false,
            ['charge_account'] = false, ['donate_account'] = false, ['save_account_note'] = false,
            ['create_inspection'] = false, ['transfer_vehicle'] = false,
        },
        ['2'] = {
            ['citizens'] = true,
            ['vehicles'] = true,
            ['reports'] = true,
            ['courts'] = true,
            ['inspections'] = true,
            ['companies'] = true,
            ['finances'] = true,
            ['announcements'] = true,
            ['employees'] = true,
            ['society'] = false,
            ['police_records'] = true,

            ['send_citizen_message'] = true,
            ['add_citizen_license'] = true, ['remove_citizen_license'] = true,
            ['change_citizen_picture'] = true, ['add_citizen_note'] = true, ['delete_citizen_note'] = true,
            ['add_citizen_tag'] = true, ['delete_citizen_tag'] = true,
            ['fire_player'] = false, ['hire_player'] = false, ['promote_player'] = false,
            ['create_announcement'] = false, ['delete_announcement'] = false,
            ['change_company_picture'] = false,
            ['withdraw_money'] = false, ['deposit_money'] = false, ['account_balance'] = false,
            ['society_transactions'] = false, ['society_chart'] = false,
            ['charge_account'] = false, ['donate_account'] = false, ['save_account_note'] = true,
            ['create_inspection'] = true, ['transfer_vehicle'] = false,
        },
        ['3'] = {
            ['citizens'] = true,
            ['vehicles'] = true,
            ['reports'] = true,
            ['courts'] = true,
            ['inspections'] = true,
            ['companies'] = true,
            ['finances'] = true,
            ['announcements'] = true,
            ['employees'] = true,
            ['society'] = true,
            ['police_records'] = true,

            ['send_citizen_message'] = true,
            ['add_citizen_license'] = true, ['remove_citizen_license'] = true,
            ['change_citizen_picture'] = true, ['add_citizen_note'] = true, ['delete_citizen_note'] = true,
            ['add_citizen_tag'] = true, ['delete_citizen_tag'] = true,
            ['fire_player'] = false, ['hire_player'] = false, ['promote_player'] = false,
            ['create_announcement'] = true, ['delete_announcement'] = false,
            ['change_company_picture'] = false,
            ['withdraw_money'] = false, ['deposit_money'] = false, ['account_balance'] = true,
            ['society_transactions'] = true, ['society_chart'] = true,
            ['charge_account'] = true, ['donate_account'] = false, ['save_account_note'] = true,
            ['create_inspection'] = true, ['transfer_vehicle'] = true,
        },
        ['4'] = {
            ['citizens'] = true,
            ['vehicles'] = true,
            ['reports'] = true,
            ['courts'] = true,
            ['inspections'] = true,
            ['companies'] = true,
            ['finances'] = true,
            ['announcements'] = true,
            ['employees'] = true,
            ['society'] = true,
            ['police_records'] = true,

            ['send_citizen_message'] = true,
            ['add_citizen_license'] = true, ['remove_citizen_license'] = true,
            ['change_citizen_picture'] = true, ['add_citizen_note'] = true, ['delete_citizen_note'] = true,
            ['add_citizen_tag'] = true, ['delete_citizen_tag'] = true,
            ['fire_player'] = true, ['hire_player'] = true, ['promote_player'] = true,
            ['create_announcement'] = true, ['delete_announcement'] = true,
            ['change_company_picture'] = true,
            ['withdraw_money'] = false, ['deposit_money'] = true, ['account_balance'] = true,
            ['society_transactions'] = true, ['society_chart'] = true,
            ['charge_account'] = true, ['donate_account'] = true, ['save_account_note'] = true,
            ['create_inspection'] = true, ['transfer_vehicle'] = true,
        },
        ['5'] = {
            ['citizens'] = true,
            ['vehicles'] = true,
            ['reports'] = true,
            ['courts'] = true,
            ['inspections'] = true,
            ['companies'] = true,
            ['finances'] = true,
            ['announcements'] = true,
            ['employees'] = true,
            ['society'] = true,
            ['police_records'] = true,

            ['send_citizen_message'] = true,
            ['add_citizen_license'] = true, ['remove_citizen_license'] = true,
            ['change_citizen_picture'] = true, ['add_citizen_note'] = true, ['delete_citizen_note'] = true,
            ['add_citizen_tag'] = true, ['delete_citizen_tag'] = true,
            ['fire_player'] = true, ['hire_player'] = true, ['promote_player'] = true,
            ['create_announcement'] = true, ['delete_announcement'] = true,
            ['change_company_picture'] = true,
            ['withdraw_money'] = true, ['deposit_money'] = true, ['account_balance'] = true,
            ['society_transactions'] = true, ['society_chart'] = true,
            ['charge_account'] = true, ['donate_account'] = true, ['save_account_note'] = true,
            ['create_inspection'] = true, ['transfer_vehicle'] = true,
        },
    }
}
